/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Nordahl
 */
public class OutOfOrder extends javax.swing.JPanel {

    tvmGUI master;
    /**
     * Creates new form OutOfOrder
     */
    public OutOfOrder() {
        initComponents();
        //LabOutOfOrderTime.setText(master.time.toString().substring(0,19));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabOutOfOrderTitle = new javax.swing.JLabel();
        LabOutOfOrderInfo = new javax.swing.JLabel();
        LabOutOfOrderTime = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));

        LabOutOfOrderTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabOutOfOrderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabOutOfOrderTitle.setText("Ude af drift / Out of order");

        LabOutOfOrderInfo.setText(" ");

        LabOutOfOrderTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabOutOfOrderTime.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabOutOfOrderTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabOutOfOrderInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(LabOutOfOrderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabOutOfOrderInfo)
                    .addComponent(LabOutOfOrderTime))
                .addGap(231, 231, 231)
                .addComponent(LabOutOfOrderTitle)
                .addContainerGap(315, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabOutOfOrderInfo;
    private javax.swing.JLabel LabOutOfOrderTime;
    private javax.swing.JLabel LabOutOfOrderTitle;
    // End of variables declaration//GEN-END:variables
}
