/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Test;

import GUI.*;
import java.awt.Color;

/**
 *
 * @author Qess
 */
public class EditAccountAdminPanel extends javax.swing.JPanel {
    private GUIFrame frame;
    private boolean inputError;
    private int errors = 1;
    /**
     * Creates new form ForgotPassControllerPanel
     */
    public EditAccountAdminPanel() {
        initComponents();
    }

    public void setFrame(GUI.Test.GUIFrame frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitle = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        labInformation1 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        labErrorEmail = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labTitle.setText("Edit Customer Account");

        labEmail.setText("Email");

        labInformation1.setText("Enter the customers email to get access to their account. ");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        labErrorEmail.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        labErrorEmail.setText("- No customer with this email found");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labInformation1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNext)
                        .addGap(26, 26, 26)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labEmail)
                        .addGap(18, 18, 18)
                        .addComponent(labErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTitle))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labInformation1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEmail)
                    .addComponent(labErrorEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        labErrorEmail.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       frame.changePanel("card11");
       labEmail.setForeground(Color.BLACK);
       textEmail.setText("");
       labErrorEmail.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        inputCheck();
        if (errors == 0){
            frame.cManager.admLoggedInAs(textEmail.getText());
            frame.changePanel("card13");
            textEmail.setText("");
        }
        errors = 1;
    }//GEN-LAST:event_btnNextActionPerformed

    private void inputCheck(){
       if(!textEmail.getText().equals("")){
            if (isValidEmailAddress(textEmail.getText()) == true){
                labEmail.setForeground(Color.BLACK);
                labErrorEmail.setVisible(false);
                errors--;
            } else{
                labEmail.setForeground(Color.RED);
                labErrorEmail.setVisible(true);
            }
        } else{
            labEmail.setForeground(Color.RED);
            labErrorEmail.setVisible(true);
        }
    }
    // Metod found at StackOverflow.com, which validates the syntax of an emailadress
    // http://stackoverflow.com/questions/624581/what-is-the-best-java-email-address-validation-method
    private boolean isValidEmailAddress(String email) {
       java.util.regex.Pattern p = java.util.regex.Pattern.compile(".+@.+\\.[a-z]+");
       java.util.regex.Matcher m = p.matcher(email);
       return m.matches();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labErrorEmail;
    private javax.swing.JLabel labInformation1;
    private javax.swing.JLabel labTitle;
    private javax.swing.JTextField textEmail;
    // End of variables declaration//GEN-END:variables
}
