/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;


/**
 *
 * @author AndreasStensig
 */
public class SaleDetailsViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChargingStationListViewPanel
     */
    public SaleDetailsViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labSaleDetails = new javax.swing.JLabel();
        labInformation = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(402, 302));

        labSaleDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labSaleDetails.setText("Sale overview");

        labInformation.setText("Below you can see a detailed overview over a billing- or deposit instance.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labSaleDetails)
                    .addComponent(labInformation))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labSaleDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labInformation;
    private javax.swing.JLabel labSaleDetails;
    // End of variables declaration//GEN-END:variables
}
