/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;


/**
 *
 * @author AndreasStensig
 */
public class SaleDepositViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChargingStationListViewPanel
     */
    public SaleDepositViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textDepositNumber = new javax.swing.JTextField();
        labDepositNumber = new javax.swing.JLabel();
        labNewBalance = new javax.swing.JLabel();
        textNewBalance = new javax.swing.JTextField();
        labDKK2 = new javax.swing.JLabel();
        lapDepositDate = new javax.swing.JLabel();
        textDepositDate = new javax.swing.JTextField();
        labDepositAmount = new javax.swing.JLabel();
        textDepositAmount = new javax.swing.JTextField();
        labLast4CardNumber = new javax.swing.JLabel();
        textLast4CardNumber = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(402, 302));

        textDepositNumber.setEditable(false);
        textDepositNumber.setText(" ");

        labDepositNumber.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labDepositNumber.setText("Deposit number");

        labNewBalance.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labNewBalance.setText("New balance");

        textNewBalance.setEditable(false);
        textNewBalance.setText("  ");

        labDKK2.setText("DKK");

        lapDepositDate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lapDepositDate.setText("Deposit date");

        textDepositDate.setEditable(false);
        textDepositDate.setText(" ");

        labDepositAmount.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labDepositAmount.setText("Deposit amount");

        textDepositAmount.setEditable(false);
        textDepositAmount.setText(" ");

        labLast4CardNumber.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labLast4CardNumber.setText("Last four card numbers");

        textLast4CardNumber.setEditable(false);
        textLast4CardNumber.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labDepositAmount)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textDepositAmount)
                                .addComponent(textDepositDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textDepositNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labDepositNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addComponent(lapDepositDate))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labDKK2))
                            .addComponent(labLast4CardNumber)
                            .addComponent(textLast4CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDepositNumber)
                    .addComponent(labNewBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDepositNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDKK2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lapDepositDate)
                    .addComponent(labLast4CardNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDepositDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLast4CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labDepositAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labDKK2;
    private javax.swing.JLabel labDepositAmount;
    private javax.swing.JLabel labDepositNumber;
    private javax.swing.JLabel labLast4CardNumber;
    private javax.swing.JLabel labNewBalance;
    private javax.swing.JLabel lapDepositDate;
    private javax.swing.JTextField textDepositAmount;
    private javax.swing.JTextField textDepositDate;
    private javax.swing.JTextField textDepositNumber;
    private javax.swing.JTextField textLast4CardNumber;
    private javax.swing.JTextField textNewBalance;
    // End of variables declaration//GEN-END:variables
}
